#!/bin/sh
# Shell
sudo pacman --noconfirm -S zsh
chsh -s $(which zsh)
sudo pacman --noconfirm -S noto-fonts noto-fonts-emoji ttf-firacode-nerd htop ranger curl man ufw 
# usbutils
sudo systemctl enable ufw
sudo ufw default deny

# Hyprland
sudo pacman --noconfirm -S pipewire pipewire-pulse pipewire-jack hyprland kitty swaybg brightnessctl pamixer python-pillow mpv swaylock veracrypt ffmpegthumbnailer jq imagemagick mediainfo
# fprintd
sudo pacman --noconfirm -S chromium yt-dlp
sudo sed -i "s/Exec=\/usr\/bin\/chromium/Exec=\/usr\/bin\/chromium --enable-features=UseOzonePlatform --ozone-platform=wayland/g" /usr/share/applications/chromium.desktop
sudo pacman --noconfirm -S greetd greetd-tuigreet
sudo sed -i "s/command = "'"'"agreety --cmd \/bin\/sh/command = "'"'"tuigreet --cmd \/usr\/bin\/Hyprland/g" /etc/greetd/config.toml
sudo systemctl enable greetd.service


# Sublime
curl -O https://download.sublimetext.com/sublimehq-pub.gpg && sudo pacman-key --add sublimehq-pub.gpg && sudo pacman-key --lsign-key 8A8F901A && rm sublimehq-pub.gpg
echo -e "\n[sublime-text]\nServer = https://download.sublimetext.com/arch/stable/x86_64" | sudo tee -a /etc/pacman.conf
sudo pacman --noconfirm -Sy sublime-merge sublime-text

IFS=$'\n'; set -f
for f in $(find ./home/user); do 
	fileName="${f/.\/home\/user/}"
	if [[ -d $f ]]; then
		if [ -z "$fileName" ]; then
			continue
		fi

		echo "mkdir ~$fileName"
		mkdir "~$fileName" 
	elif [[ -f $f ]]; then
		echo "ln $f ~$fileName"
		ln "$f" "~$fileName"
	fi
done
unset IFS; set +f

