#!/bin/sh
# Shell
sudo pacman -S zsh
chsh -s $(which zsh)
sudo pacman -S noto-fonts noto-fonts-emoji ttf-firacode-nerd htop ranger curl man

# Hyprland
sudo pacman -S pipewire pipewire-pulse pipewire-jack hyprland kitty swaybg brightnessctl pamixer mpv

sudo pacman -S chromium
sudo pacman -S yt-dlp

# Sublime
curl -O https://download.sublimetext.com/sublimehq-pub.gpg && sudo pacman-key --add sublimehq-pub.gpg && sudo pacman-key --lsign-key 8A8F901A && rm sublimehq-pub.gpg
echo -e "\n[sublime-text]\nServer = https://download.sublimetext.com/arch/stable/x86_64" | sudo tee -a /etc/pacman.conf
sudo pacman -Syu sublime-merge

