#!/bin/sh
# Shell
sudo pacman --noconfirm -S zsh
chsh -s $(which zsh)
sudo pacman --noconfirm -S noto-fonts noto-fonts-emoji ttf-firacode-nerd htop ranger curl man

# Hyprland
sudo pacman --noconfirm -S pipewire pipewire-pulse pipewire-jack hyprland kitty swaybg brightnessctl pamixer mpv
sudo pacman --noconfirm -S chromium yt-dlp

# Sublime
curl -O https://download.sublimetext.com/sublimehq-pub.gpg && sudo pacman-key --add sublimehq-pub.gpg && sudo pacman-key --lsign-key 8A8F901A && rm sublimehq-pub.gpg
echo -e "\n[sublime-text]\nServer = https://download.sublimetext.com/arch/stable/x86_64" | sudo tee -a /etc/pacman.conf
sudo pacman --noconfirm -Sy sublime-merge sublime-text

IFS=$'\n'; set -f
for f in $(find ./home/user); do 
	fileName="${f/.\/home\/user/}"
	if [[ -d $f ]]; then
		if [ -z "$fileName" ]; then
			continue
		fi

		echo "mkdir ~$fileName"
		mkdir "~$fileName" 
	elif [[ -f $f ]]; then
		echo "ln $f ~$fileName"
		ln "$f" "~$fileName"
	fi
done
unset IFS; set +f

